config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :customers
  root 'customers#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
     validates :CustomerName, presence: true,
                    length: { maximum: 50 }
     validates :Industry, presence: true,
                    length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
     validates :Email, presence: true,
                    length: { maximum: 255 },
                    format: {with: VALID_EMAIL_REGEX},
                    uniqueness: { case_sensitive: false }
     validates :Phone, presence: true,
                    length: { minimum: 5, maximum: 20 }
     validates :Notes, presence: true,
                    length: { minimum: 5 }, allow_nil: true 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
    
    def index
       @customers = Customer.all 
    end
    
    def show
       @customer = Customer.find(params[:id]) 
    end
    
    def edit
       @customer = Customer.find(params[:id]) 
    end
    
    def new 
        @customer = Customer.new
    end
    
    def create 
        @customer = Customer.new(customer_params)
        if @customer.save
            redirect_to @customer
        else
            render 'new'
        end
    end
    
    def update
        @customer = Customer.find(params[:id])
        if @customer.update(customer_params)
            redirect_to @customer
        else
            render 'edit'
        end
    end
    
    def destroy
       @customer = Customer.find(params[:id])
       @customer.destroy
       
       redirect_to customers_path
    end
    
    private 
    
    def customer_params
        params.require(:customer).permit(:CustomerName, :Industry, :Email, :Phone, :Notes) 
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<%= form_for @customer do |f| %>
<% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@customer.errors.count, "error") %> prohibited
        this customer from being saved:
      </h2>
      <ul>
        <% @customer.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <p>
    <%= f.label :Name %><br>
    <%= f.text_field :CustomerName %>
  </p>
  
  <p>
    <%= f.label :Industry %><br>
    <%= f.text_field :Industry %>
  </p>
  
  <p>
    <%= f.label :Email %><br>
    <%= f.text_field :Email %>
  </p>
  
  <p>
    <%= f.label :Phone %><br>
    <%= f.text_field :Phone %>
  </p>
 
  <p>
    <%= f.label :Notes %><br>
    <%= f.text_area :Notes %>
  </p>
 
  <p>
    <%= f.submit class: "btn btn-primary" %>
  </p>
<% end %>

app/views/customers/edit.html.erb
<%= render 'form' %> 
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<h1>Listing customers</h1>

<%= link_to 'New Customer', new_customer_path %>
 
<table class="table table-bordered">
  <tr>
    <th>Customer Name</th>
    <th>Industry</th>
    <th>Email</th>
    <th>Phone</th>
    <th>Notes</th>
    <th>Show</th>
    <th>Edit</th>
    <th>Delete</th>
  </tr>
 
  <% @customers.each do |customer| %>
    <tr>
      <td><%= customer.CustomerName %></td>
      <td><%= customer.Industry %></td>
       <td><%= customer.Email %></td>
        <td><%= customer.Phone %></td>
         <td><%= customer.Notes %></td>
      <td><%= link_to 'Show', customer_path(customer) %></td>
      <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
      <td><%= link_to 'Delete', customer_path(customer),
                    method: :delete,
                    data: {confirm: 'Are you sure?'} %></td>
    </tr>
  <% end %>
</table>

app/views/customers/new.html.erb
<%= render 'form' %> 
<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @customer.CustomerName %>
</p>
 
<p>
  <strong>Industry:</strong>
  <%= @customer.Industry %>
</p>

<p>
  <strong>Email:</strong>
  <%= @customer.Email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @customer.Phone %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @customer.Notes %>
</p>

<%= link_to 'Edit', edit_customer_path(@customer) %>
<%= link_to 'Back', customers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PmApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->
  </head>

  <body>
   
  <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <a class="navbar-brand" href="#">Logo</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Home</a></li>
        <li><a href="#">About</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
      </ul>
    </div>
  </div>
</nav>
  
<div class="container-fluid text-center">    
  <div class="row content">
    <div class="col-sm-2 sidenav">
      <p><a href="#">Link</a></p>
      <p><a href="#">Link</a></p>
      <p><a href="#">Link</a></p>
    </div>
    <div class="col-sm-8 text-left"> 
         <%= yield %>
    </div>
     
  </div>
</div>

<footer class="container-fluid text-center">
  <p>Footer Text</p>
</footer>
    
  </body>
</html>